### ISSUE TITLE
반영을 못하겠다

### ISSUE THREAD

**Issue by spinel0608** [layland/AStudy#1]
고쳤는데 반영이 안되네여
지형이는 집에 가서 git remote -v를 쳐주세여 'ㅅ'

**Comment by layland** [comment]
$ git remote -v
github  https://github.com/layland/AStudy.git (fetch)
github  https://github.com/layland/AStudy.git (push)
origin  https://github.com/layland/test.git (fetch)
origin  https://github.com/layland/test.git (push)
study   https://github.com/layland/Astudy.git (fetch)
study   https://github.com/layland/Astudy.git (push)

뭐지이건..

**Comment by spinel0608** [comment]
http://forum.openframeworks.kr/t/1-git/81/2
